#!/usr/bin/env bash
#
# Prepares the local test infrastructure for E2E tests.
# Idempotent — skips services that are already running.
#
# Usage:
#   mac% ./scripts/test-infra.sh          # start everything
#   mac% ./scripts/test-infra.sh --seed   # also reset DB and seed test data
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SEED_FLAG="${1:-}"

# ---------- helpers ----------
info()  { echo "==> $*"; }
warn()  { echo "    (already running, skipping)"; }
die()   { echo "ERROR: $*" >&2; exit 1; }

# ---------- prerequisite checks ----------
command -v supabase >/dev/null 2>&1 || die "supabase CLI not found. Install: brew install supabase/tap/supabase"
command -v livekit-server >/dev/null 2>&1 || die "livekit-server not found. Install: brew install livekit"
command -v psql >/dev/null 2>&1 || die "psql not found. Install: brew install libpq && brew link --force libpq"
docker info >/dev/null 2>&1 || die "Docker is not running. Start Colima first: colima start --memory 4 --cpu 2"

cd "$PROJECT_DIR"

# ---------- 1. Supabase ----------
info "Checking Supabase..."
if curl -so /dev/null -w '%{http_code}' http://127.0.0.1:54321 2>/dev/null | grep -q '[2-4]'; then
  warn
else
  info "Starting local Supabase..."
  supabase start
fi

# Capture Supabase publishable key
# The status output uses box-drawing chars: │ Publishable │ sb_publishable_... │
# We extract the key by splitting on │ and trimming whitespace.
SUPABASE_URL="http://127.0.0.1:54321"
PUB_KEY=$(supabase status 2>/dev/null | grep -i "Publishable" | sed 's/│/|/g' | awk -F'|' '{gsub(/^ +| +$/, "", $3); print $3}' || true)
if [ -z "$PUB_KEY" ]; then
  PUB_KEY=$(supabase status 2>/dev/null | grep "anon key" | sed 's/│/|/g' | awk -F'|' '{gsub(/^ +| +$/, "", $3); print $3}' || true)
fi

# ---------- 2. LiveKit ----------
info "Checking LiveKit..."
if curl -sf http://localhost:7880 > /dev/null 2>&1; then
  warn
  # Read key/secret from existing env.local if available
  LK_API_KEY=$(grep -s 'LIVEKIT_API_KEY=' "$PROJECT_DIR/supabase/.env.local" 2>/dev/null | cut -d= -f2- || echo "devkey")
  LK_API_SECRET=$(grep -s 'LIVEKIT_API_SECRET=' "$PROJECT_DIR/supabase/.env.local" 2>/dev/null | cut -d= -f2- || echo "secret")
else
  info "Starting local LiveKit server..."
  livekit-server --dev --bind 0.0.0.0 > /tmp/livekit-dev.log 2>&1 &
  LIVEKIT_PID=$!

  info "Waiting for LiveKit to start (pid $LIVEKIT_PID)..."
  for i in {1..15}; do
    if curl -sf http://localhost:7880 > /dev/null 2>&1; then
      break
    fi
    if ! kill -0 "$LIVEKIT_PID" 2>/dev/null; then
      die "LiveKit server exited unexpectedly. Check /tmp/livekit-dev.log"
    fi
    sleep 1
  done
  curl -sf http://localhost:7880 > /dev/null 2>&1 || die "LiveKit did not start within 15 seconds. Check /tmp/livekit-dev.log"

  # Parse API key/secret from livekit dev mode log (macOS grep — no -P flag)
  LK_API_KEY=$(grep -o 'API Key: [^ ]*' /tmp/livekit-dev.log 2>/dev/null | head -1 | awk '{print $NF}' || echo "devkey")
  LK_API_SECRET=$(grep -o 'API Secret: [^ ]*' /tmp/livekit-dev.log 2>/dev/null | head -1 | awk '{print $NF}' || echo "secret")
fi

# ---------- 3. Write supabase/.env.local ----------
# supabase start loads .env.local into the edge-runtime container automatically.
# This must be written BEFORE `supabase start` for the env vars to take effect.
# If Supabase was already running, the env vars are already loaded from the
# previous start. If the secrets are wrong, run: supabase stop && ./scripts/test-infra.sh
info "Writing supabase/.env.local..."
cat > "$PROJECT_DIR/supabase/.env.local" <<ENVEOF
LIVEKIT_API_KEY=$LK_API_KEY
LIVEKIT_API_SECRET=$LK_API_SECRET
LIVEKIT_WS_URL=ws://localhost:7880
ENVEOF

# Verify livekit-token Edge Function returns a valid token
info "Verifying livekit-token Edge Function..."
EDGE_FN_OK=$(curl -sf http://127.0.0.1:54321/functions/v1/livekit-token \
  -X POST \
  -H "Content-Type: application/json" \
  -H "apikey: ${PUB_KEY:-none}" \
  -H "Authorization: Bearer ${PUB_KEY:-none}" \
  -d '{"session_id":"00000000-0000-0000-0000-000000000001","identity":"test","role":"facilitator"}' 2>/dev/null | grep -c '"token"' || echo "0")

if [ "$EDGE_FN_OK" = "1" ]; then
  info "livekit-token Edge Function is working."
else
  echo "WARNING: livekit-token returned an error. If LiveKit secrets changed,"
  echo "         run: supabase stop && ./scripts/test-infra.sh"
fi

# ---------- 4. Write .env.test ----------
info "Writing .env.test..."
cat > "$PROJECT_DIR/.env.test" <<EOF
# Test environment — auto-generated by scripts/test-infra.sh
VITE_SUPABASE_URL="$SUPABASE_URL"
VITE_SUPABASE_PUBLISHABLE_KEY="${PUB_KEY:-UNKNOWN_KEY}"
VITE_LIVEKIT_WS_URL="ws://localhost:7880"
EOF

# ---------- 5. Seed test data (optional) ----------
if [ "$SEED_FLAG" = "--seed" ]; then
  info "Resetting database and seeding test data..."
  supabase db reset
  psql "postgresql://postgres:postgres@127.0.0.1:54322/postgres" -f "$PROJECT_DIR/tests/fixtures/seed.sql"
else
  # Check if test session exists; seed if not
  EXISTING=$(psql "postgresql://postgres:postgres@127.0.0.1:54322/postgres" -tAc \
    "SELECT count(*) FROM sessions WHERE id = '00000000-0000-0000-0000-000000000001'" 2>/dev/null || echo "0")
  if [ "$EXISTING" = "0" ]; then
    info "Test session not found — seeding test data..."
    psql "postgresql://postgres:postgres@127.0.0.1:54322/postgres" -f "$PROJECT_DIR/tests/fixtures/seed.sql"
  else
    info "Test data already present, skipping seed. Use --seed to force reset."
  fi
fi

# ---------- 5. npm dependencies ----------
if [ ! -d "$PROJECT_DIR/node_modules" ]; then
  info "Installing npm dependencies..."
  npm install
fi

# ---------- Done ----------
echo ""
info "Test infrastructure ready."
echo ""
echo "    Supabase:  $SUPABASE_URL"
echo "    LiveKit:   ws://localhost:7880"
echo "    Vite:      http://localhost:8080 (started by Playwright automatically)"
echo ""
echo "Run all E2E tests:"
echo "    mac% npx playwright test"
echo ""
echo "Run specific test suites:"
echo "    mac% npx playwright test tests/e2e/login.spec.ts"
echo "    mac% npx playwright test tests/e2e/stageFlow.spec.ts"
echo "    mac% npx playwright test tests/e2e/chat.spec.ts"
echo "    mac% npx playwright test tests/e2e/investment.spec.ts"
echo "    mac% npx playwright test tests/e2e/videoCall.spec.ts"
echo "    mac% npx playwright test tests/e2e/videoVisibility.spec.ts"
echo ""
echo "Run unit + component tests:"
echo "    mac% npm test"
echo ""
echo "Shut down when done:"
echo "    mac% ./scripts/test-infra-stop.sh"
