#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------- helpers ----------
info()  { echo "==> $*"; }
die()   { echo "ERROR: $*" >&2; exit 1; }

command -v supabase >/dev/null 2>&1 || die "supabase CLI not found. Install: brew install supabase/tap/supabase"
command -v livekit-server >/dev/null 2>&1 || die "livekit-server not found. Install: brew install livekit"
docker info >/dev/null 2>&1 || die "Docker is not running. Start Colima first: colima start --memory 4 --cpu 2"

# ---------- Start Supabase ----------
info "Starting local Supabase..."
cd "$PROJECT_DIR"
supabase start

# Capture Supabase credentials
SUPABASE_URL="http://127.0.0.1:54321"

# Try the newer CLI key name (Publishable), fall back to legacy (anon key)
PUB_KEY=$(supabase status 2>/dev/null | grep -i "Publishable" | awk '{print $NF}')
if [ -z "$PUB_KEY" ]; then
  PUB_KEY=$(supabase status -o env 2>/dev/null | grep ANON_KEY | head -1 | cut -d= -f2-)
fi
if [ -z "$PUB_KEY" ]; then
  PUB_KEY=$(supabase status 2>/dev/null | grep "anon key" | awk '{print $NF}')
fi

if [ -z "$PUB_KEY" ]; then
  echo "WARNING: Could not auto-detect publishable key. Run 'supabase status' and update .env.test manually."
else
  info "Writing .env.test with local Supabase credentials..."
  cat > "$PROJECT_DIR/.env.test" <<EOF
# Test environment — auto-generated by scripts/test-infra.sh
VITE_SUPABASE_URL="$SUPABASE_URL"
VITE_SUPABASE_PUBLISHABLE_KEY="$PUB_KEY"
VITE_LIVEKIT_WS_URL="ws://localhost:7880"
EOF
fi

# ---------- Start LiveKit ----------
info "Starting local LiveKit server..."

# Kill any existing livekit-server on port 7880
lsof -ti :7880 | xargs kill -9 2>/dev/null || true

# Start in dev mode (generates ephemeral key/secret, prints them)
livekit-server --dev --bind 0.0.0.0 > /tmp/livekit-dev.log 2>&1 &
LIVEKIT_PID=$!

# Wait for LiveKit to be ready
info "Waiting for LiveKit to start (pid $LIVEKIT_PID)..."
for i in {1..15}; do
  if curl -sf http://localhost:7880 > /dev/null 2>&1; then
    break
  fi
  if ! kill -0 $LIVEKIT_PID 2>/dev/null; then
    die "LiveKit server exited unexpectedly. Check /tmp/livekit-dev.log"
  fi
  sleep 1
done

curl -sf http://localhost:7880 > /dev/null 2>&1 || die "LiveKit did not start within 15 seconds. Check /tmp/livekit-dev.log"

# Parse API key/secret from livekit dev mode log
LK_API_KEY=$(grep -oP 'API Key: \K\S+' /tmp/livekit-dev.log 2>/dev/null || grep -o 'API Key: [^ ]*' /tmp/livekit-dev.log 2>/dev/null | awk '{print $NF}' || echo "devkey")
LK_API_SECRET=$(grep -oP 'API Secret: \K\S+' /tmp/livekit-dev.log 2>/dev/null || grep -o 'API Secret: [^ ]*' /tmp/livekit-dev.log 2>/dev/null | awk '{print $NF}' || echo "secret")

info "Writing supabase/.env.local with LiveKit credentials..."
cat > "$PROJECT_DIR/supabase/.env.local" <<EOF
# Local LiveKit secrets — auto-generated by scripts/test-infra.sh
LIVEKIT_API_KEY=$LK_API_KEY
LIVEKIT_API_SECRET=$LK_API_SECRET
LIVEKIT_WS_URL=ws://localhost:7880
EOF

# ---------- Seed test data ----------
info "Resetting database and seeding test data..."
supabase db reset

# Get DATABASE_URL for psql
DB_URL=$(supabase status -o env 2>/dev/null | grep DATABASE_URL | cut -d= -f2- || echo "")

if [ -n "$DB_URL" ]; then
  psql "$DB_URL" -f "$PROJECT_DIR/tests/fixtures/seed.sql"
else
  # Fallback: use default local Supabase postgres URL
  psql "postgresql://postgres:postgres@localhost:54322/postgres" -f "$PROJECT_DIR/tests/fixtures/seed.sql"
fi

# ---------- Done ----------
echo ""
info "Infrastructure ready."
echo "    Supabase:  $SUPABASE_URL"
echo "    LiveKit:   ws://localhost:7880"
echo "    LiveKit PID: $LIVEKIT_PID"
echo ""
echo "Run the dev server against local services:"
echo "    npx vite --mode test --port 8080"
echo ""
echo "Run tests with:"
echo "    npx playwright test"
echo ""
echo "Stop LiveKit with:"
echo "    kill $LIVEKIT_PID"
echo ""
echo "Stop Supabase with:"
echo "    supabase stop"
